# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73b4dc80b4314a5141cda7ac909458e3ff0add2ff10c909c3e4149ececae6ffe34e4e3e2742aa691fe749c24cdeabbc27c3780ac1fd6c978fe19d8aad6c4e95d

test:
  secret_key_base: da50063c5688352beb83edfbdb8ccd0289f717ca77a4087300d27eead1804e3308640e6a17b995d46179586865da57f050b141bc8f5997a23337a55979bf8124

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
